trigger:
- main

pool: 'andris-azure-agent-pool'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'twitter-clone'

- script: |
    cd twitter-clone
    ng build
  displayName: 'Build Angular App'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/twitter-clone/dist/twitter-clone'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx'
    testRunTitle: 'Unit tests'

# Publish Angular App
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(35aab0f4-925a-4940-b144-1d8cca2f274a)'
    appType: 'webApp'
    WebAppName: 'TwitterCloneUI'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- script: |
    ls $(Build.ArtifactStagingDirectory)
  displayName: 'List build artifacts'

# Publish .NET Core App
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(35aab0f4-925a-4940-b144-1d8cca2f274a)'
    appType: 'webApp'
    WebAppName: 'TwitterCloneApi'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/TwitterClone.zip'
